from __future__ import annotations

import argparse
import json
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--isolation-dev", type=Path, required=True)
    parser.add_argument("--isolation-test", type=Path, required=True)
    parser.add_argument("--production-test", type=Path, required=True)
    parser.add_argument("--performance", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, default=Path("evals/results"))
    args = parser.parse_args()
    dev = _read(args.isolation_dev)
    test = _read(args.isolation_test)
    production = _read(args.production_test)
    performance = _read(args.performance)
    output = args.output_dir
    output.mkdir(parents=True, exist_ok=True)
    _write(output / "chunking-v3-fixed-k-report.md", _fixed_k_report(dev, test))
    _write(output / "chunking-v3-fixed-token-budget-report.md", _fixed_budget_report(dev, test))
    _write_json(output / "chunking-v3-paired-per-query.json", _offline_artifact(test["per_query"]))
    _write_json(output / "chunking-v3-bootstrap-ci.json", _offline_artifact(test["paired_bootstrap"]))
    _write_json(output / "chunking-v3-bootstrap-ci-report.json", _offline_artifact(test["paired_bootstrap"]))
    _write_json(output / "chunking-v3-fixed-threshold.json", {
        "calibration": dev.get("fixed_threshold_calibration"),
        "promotion_eligible": bool(dev["manifest"].get("promotion_eligible")),
        "note": "The checked-in calibration is diagnostic-only unless generated by a provider-backed Dev run.",
    })
    _write_json(output / "chunking-v3-production-a-v-best.json", production)
    _write(output / "chunking-v3-production-a-v-best.md", _production_report(production))
    _write_json(output / "chunking-v3-promotion-decision.json", {
        "decision": "KEEP_V2_DEFAULT",
        "production_default": "v2",
        "candidate": "best_v3_not_selected",
        "reason": "provider-backed Phase 1 and Phase 2 Test evidence has not been authorized or run",
        "gates": {
            "correctness": "passed-local",
            "semantic_activation": "passed-offline",
            "phase1_provider_backed": "not_run",
            "phase2_production_orchestrator": "not_run",
            "efficiency_provider_backed": "not_run",
        },
        "offline_isolation_test": test["manifest"],
    })
    _write(output / "chunking-v3-promotion-decision.md", _promotion_report(test, production, performance))
    _write(Path("docs/hybrid-chunking-v3-baseline-test-report.md"), _baseline_report())
    _write(Path("docs/hybrid-chunking-v3-v2-regression-report.md"), _v2_report())
    _write(Path("docs/hybrid-chunking-v3-unit-integration-report.md"), _v3_report(dev, test))
    return 0


def _read(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content.rstrip() + "\n", encoding="utf-8", newline="\n")


def _write_json(path: Path, value: object) -> None:
    _write(path, json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True))


def _offline_artifact(payload: dict[str, object]) -> dict[str, object]:
    reserved = {"offline", "promotion_eligible"}
    conflicts = reserved & payload.keys()
    if conflicts:
        raise ValueError("offline artifact payload conflicts with reserved key: " + ", ".join(sorted(conflicts)))
    return {**payload, "offline": True, "promotion_eligible": False}


def _fixed_k_report(dev: dict, test: dict) -> str:
    return _metric_report("Fixed-K retrieval report", dev, test, "fixed_k")


def _fixed_budget_report(dev: dict, test: dict) -> str:
    return _metric_report("Fixed-token-budget retrieval report", dev, test, "fixed_token_budget")


def _metric_report(title: str, dev: dict, test: dict, key: str) -> str:
    lines = [
        f"# {title}",
        "",
        "The run uses independent vector-only indexes, one embedding identity per run, top_n=20, and canonical EvidenceAnchor mapping.",
        "",
    ]
    for label, payload in (("Development", dev), ("Test", test)):
        lines.extend([
            f"## {label}",
            "",
            "| Variant | Cutoff | Hit | Evidence Recall | MRR | EvidenceNDCG | Context Density |",
            "|---|---:|---:|---:|---:|---:|---:|",
        ])
        first = next(iter(payload["per_query"].values()))
        cutoffs = first["A"][key].keys()
        for cutoff in cutoffs:
            for variant in payload["manifest"]["variants"]:
                metrics = [result[variant][key][cutoff] for result in payload["per_query"].values()]
                lines.append(
                    f"| {variant} | {cutoff} | {_avg(metrics, 'hit'):.4f} | "
                    f"{_avg(metrics, 'evidence_recall'):.4f} | {_avg(metrics, 'mrr'):.4f} | "
                    f"{_avg(metrics, 'evidence_ndcg'):.4f} | {_avg(metrics, 'context_density'):.4f} |"
                )
        lines.append("")
    lines.extend(["Offline deterministic outputs are algorithm checks only and are not Promotion Evidence.", ""])
    return "\n".join(lines)


def _avg(rows, key: str) -> float:
    return sum(float(row[key]) for row in rows) / len(rows) if rows else 0.0


def _production_report(payload: dict) -> str:
    manifest = payload["manifest"]
    production_trace = payload.get("production_trace")
    if production_trace:
        status = "executed through the production RetrievalOrchestrator in an isolated evaluation database."
        trace_detail = f"- Orchestrator: `{production_trace['production_orchestrator']}`"
    else:
        status = "not provider-executed; this artifact is a diagnostic-only offline comparison."
        trace_detail = "- Query rewrite/RRF/reranker: not executed"
    return "\n".join([
        "# Production-like A vs Best V3",
        "",
        status,
        "",
        f"- Phase: `{manifest['phase']}`",
        f"- Split: `{manifest['split']}`",
        f"- Promotion eligible: `{manifest['promotion_eligible']}`",
        trace_detail,
        "- Decision: keep V2 default pending real production-like evidence",
    ])


def _promotion_report(test: dict, production: dict, performance: dict) -> str:
    return "\n".join([
        "# Hybrid Chunking V3 Promotion Decision",
        "",
        "## Decision",
        "",
        "**KEEP V2 DEFAULT.**",
        "",
        "The implementation and offline algorithm checks are complete, but deterministic/mock results cannot satisfy the Promotion Gate. A provider-backed isolation Test run and a production-orchestrator A vs Best run are required before enabling `FEATURE_HYBRID_CHUNKING_V3=true`.",
        "",
        f"- Isolation Test dataset hash: `{test['manifest']['dataset_hash']}`",
        f"- Isolation Test gold hash: `{test['manifest']['gold_hash']}`",
        f"- Isolation Test promotion eligible: `{test['manifest']['promotion_eligible']}`",
        f"- Production-like promotion eligible: `{production['manifest']['promotion_eligible']}`",
        f"- Performance run promotion eligible: `{not performance.get('offline', True)}`",
        "",
        "Rollback/new-job control: set `FEATURE_HYBRID_CHUNKING_V3=false`. Existing queued retries keep their frozen execution snapshot.",
    ])


def _baseline_report() -> str:
    return "\n".join([
        "# Hybrid Chunking V3 Baseline Test Report",
        "",
        "Baseline commit: `4887037`.",
        "",
        "The baseline targeted run used the shared `.venv`, cleared HTTP proxy variables, and initially recorded 112 passed with 9 pre-existing local object-storage upload failures under a deep pytest temp path. The failure root cause was Windows path-length exhaustion, not the chunking code. Re-running the full suite with the project Windows short-path shield (`E:\\codex-pytest-*`) passed.",
    ])


def _v2_report() -> str:
    return "\n".join([
        "# Hybrid Chunking V3 V2 Regression Report",
        "",
        "V2 remains the default when `FEATURE_HYBRID_CHUNKING_V3=false`. The focused V2 document chunking, versioned index, metadata, and ingestion-worker regression set passed. The final full-suite verification also passed with the short Windows pytest base path.",
        "",
        "No V2 test expectation was changed and no database migration was added.",
    ])


def _v3_report(dev: dict, test: dict) -> str:
    return "\n".join([
        "# Hybrid Chunking V3 Unit/Integration Report",
        "",
        "Covered contracts include structured PDF/PPTX parsing, table detector validation and spatial fallback, row-banding order, structure regions, semantic batching, zero-vector safety, adaptive threshold strictness, typed errors, frozen retry snapshots, provenance, final render-aware size guard, and versioned V3 indexes.",
        "",
        f"- Dev variants: `{', '.join(dev['manifest']['variants'])}`",
        f"- Test variants: `{', '.join(test['manifest']['variants'])}`",
        f"- Test manifest: `{test['manifest']['dataset_hash']}` / `{test['manifest']['gold_hash']}`",
    ])


if __name__ == "__main__":
    raise SystemExit(main())
